#!/bin/bash

module load intel/18.0.3

echo "Running make..."
make -f ManualMakefile lab09 || { exit 1; }

echo "Executing built binary..."
tput setaf 2 2> /dev/null

N=20000

if hash srun 2>/dev/null; then
    srun -t1 -N2 --ntasks-per-node=2 ./lab09 ${N}
else
    mpirun -n 4 ./lab09 ${N}
fi


tput sgr0 2> /dev/null