#!/bin/bash

module load intel/18.0.3
module load compiler/GCC/8.2.0-2.31.1

echo "Running make..."
make -j8 -f ManualMakefile lab08 || { exit 1; }

echo "Executing built binary..."
tput setaf 2 2> /dev/null

if hash srun 2>/dev/null; then
    srun -t1 -N1 ./lab08
else
    ./lab08
fi


tput sgr0 2> /dev/null