#!/bin/bash

trap "exit" INT

module load intel/18.0.3

echo "Running make..."
make -f ManualMakefile lab05 || { exit 1; }

echo "Executing built binary..."
tput setaf 2 2> /dev/null

MAX_THREADS=$((`grep -c ^processor /proc/cpuinfo` * 2 ))
STEPSIZE=4
TOSSES=1000000000

rm -f measurements.txt

MAX_I=$(($MAX_THREADS / $STEPSIZE))
for I in `seq 0 ${MAX_I}`;
do
    THREADS=$((1 + $I * $STEPSIZE))
    echo "Running with $THREADS thread(s)"
    printf "$THREADS " | tee measurements.txt
    if hash srun 2>/dev/null; then
        srun -t1 -N1 -n1 ./lab05 ${TOSSES} ${THREADS} | tail -n 1 | tee measurements.txt
    else
        ./lab05 ${TOSSES} ${THREADS} | tail -n 1 | tee measurements.txt
fi
done

tput sgr0 2> /dev/null