#!/bin/bash

module load intel/18.0.3

echo "Running make..."
make -f ManualMakefile lab08 || { exit 1; }

echo "Executing built binary..."
tput setaf 2 2> /dev/null

export OMP_SCHEDULE="static"
export OMP_NUM_THREADS=40

if hash srun 2>/dev/null; then
    srun -t1 -N1 ./lab08
else
    ./lab08
fi


tput sgr0 2> /dev/null